// these colors are exposed by the styled-components ThemeProvider
// and used within the application
export default {
  success: "#00ff00",
  successLighter: "rgba(153, 255, 153, 0.25)",
  error: "#FF0000",
  errorLighter: "rgba(255,153,153, 0.4)",
  background: "linear-gradient(270deg, #196ebd, #01b0dd)",
  baseButton: "#FFFFFF",
  baseButtonDisabled: "rgba(216,216,216, 0.5)",
  info: "#bdbdbd",
  title: "#FFFFFF",
  secondary: "#d3d3d3",
  border: "#ccc",
  shadow: "rgba(0, 0, 0, 0.17)",
  turtleEnableBar: "#ededed",
  turtleEnableButton: "#ededed",
  turtleEnableButtonActive: "silver",
  bottomBarButton: "#ededed",
  bottomBarButtonActive: "silver",
  notificationSuccess: "green",
  notificationWarning: "#ffcc00",
  notificationError: "Tomato",
  dropBallButton: "#ededed",
  dropBallButtonActive: "silver",
  inOutButton: "#ededed",
  inOutButtonActive: "silver",
  refboxMagenta: "magenta",
  refboxCyan: "cyan",
  refboxMagentaActive: "magenta",
  refboxCyanActive: "cyan"
};
